### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/vscode-jsonp#5]
Syntax highlighting should be aligned a little bit. See attached PDF.
[Findings.pdf](https://github.com/test-fullautomation/vscode-jsonp/files/11753788/Findings.pdf)

**Comment by test-fullautomation** [comment]
first issue solved and already merged with  #6

**Comment by test-fullautomation** [comment]
second issue (dot-syntax has different color) is not solved => repoened

**Comment by test-fullautomation** [comment]
solved and already merged with #7
